### ISSUE TITLE
TUM Dataset - Missing CameraTrajectory.txt and KeyFrameTrajectory.txt

### ISSUE THREAD

**Issue by FraDePace** [luigifreda/plvs#42]
When I try the example of the TUM RGB-D datasets, I get some errors related to missing `Scripts/CameraTrajectory.txt` and` Scripts/KeyFrameTrajectory.txt` files.
I think the error happens when the `evaluate_tum.sh` calls the following python command
`python3 $EVALUATE_SCRIPT --verbose $GROUDTRUTH_DATA_PATH $TRAJECTORY_PATH/CameraTrajectory.txt --save_transformation transformation.txt --plot CameraTrajectory.png`

and I do not understand why `evaluate_ate.py` tries to associate (using `associate.py`) the ground-truth with the estimated trajectory.
Shouldn't `associate.py` be used to associate the RGB and depth frames?

I have downloaded the TUM rgbd_dataset_freiburg1_xyz dataset, this is its structure:
<img width="305" alt="Capture" src="https://github.com/user-attachments/assets/cdd474e8-9954-4569-ae12-d7e4ebe1f23c" />

the DATASET_PATH is correct.

this is the output of `evaluate_tum.sh`:

`francesco@DESKTOP-VEDIO76:~/Projects/plvs/Scripts$ ./run_tum_rgbd.sh`
`using TUM1 settings`
`DATASET_PATH: /home/francesco/dataset/rgbd_dataset_freiburg1_xyz`
`Viewer.on: 1`

`PLVS2`
`This program comes with ABSOLUTELY NO WARRANTY;`
`This is free software, and you are welcome to redistribute it`
`under certain conditions. See LICENSE.txt.`

`Input sensor was set to: RGB-D`

```
Loading ORB Vocabulary. This could take a while...
./run_tum_rgbd.sh: line 82:  2597 Killed                  $DEBUG_PREFIX ../Examples$SUFFIX/RGB-D/rgbd_tum$SUFFIX ../Vocabulary/ORBvoc.txt ../Examples$SUFFIX/RGB-D/$TUM_YAML $DATASET_PATH $DATASET_PATH/associations.txt
```
```
...
DATASET_PATH: /home/francesco/dataset/rgbd_dataset_freiburg1_xyz
TRAJECTORY_PATH: /home/francesco/Projects/plvs/Scripts
```
```
Traceback (most recent call last):
  File "/home/francesco/Projects/plvs/Scripts/evaluate_ate.py", line 133, in <module>
    second_list = associate.read_file_list(args.second_file)
  File "/home/francesco/Projects/plvs/Scripts/associate.py", line 64, in read_file_list
    file = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/francesco/Projects/plvs/Scripts/CameraTrajectory.txt'
Traceback (most recent call last):
  File "/home/francesco/Projects/plvs/Scripts/evaluate_ate.py", line 133, in <module>
    second_list = associate.read_file_list(args.second_file)
  File "/home/francesco/Projects/plvs/Scripts/associate.py", line 64, in read_file_list
    file = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/francesco/Projects/plvs/Scripts/KeyFrameTrajectory.txt'
mv: cannot stat 'CameraTrajectory*': No such file or directory
mv: cannot stat 'KeyFrameTrajectory*': No such file or directory
mv: cannot stat 'transformation.txt': No such file or directory
mv: cannot stat 'Performances.txt': No such file or directory
Moved output to /home/francesco/Projects/plvs/Scripts/Results/
```

**Comment by luigifreda** [comment]
Ciao Francesco,
You are getting an error here (the execution is killed):
```
./run_tum_rgbd.sh: line 82:  2597 Killed                  $DEBUG_PREFIX ../Examples$SUFFIX/RGB-D/rgbd_tum$SUFFIX ../Vocabulary/ORBvoc.txt ../Examples$SUFFIX/RGB-D/$TUM_YAML $DATASET_PATH $DATASET_PATH/associations.txt
```
The following errors you are seeing occur because the expected output files are not generated (given the execution is killed).

You can try to understand why that is happening by using `gdb` (uncomment this line in the script https://github.com/luigifreda/plvs/blob/d8a747a305eedfd63fc44e8fc6c81e893b26f880/Scripts/run_tum_rgbd.sh#L75).
Another thing you can try is to set the build type to Debug and disable march-native optimization
```
export BUILD_TYPE=Debug            # control the build type of all the projects
export BUILD_WITH_MARCH_NATIVE=OFF
```

I suspect WSL2 (that you are using under Windows) may have a role here. I am not able to support on it though. I strongly recommend using a native Linux system. Many things can go wrong on WSL2.
Yesterday I tested again PLVS under Ubuntu 20, 22, 24 (native systems and docker) and everything work correctly on them. 

LMK.

**Comment by FraDePace** [comment]
thanks, the issue is solved!

The problem was that `Examples_old/RGB-D/rgbd_tum_old` could not find the `Vocabulary/ORBvoc.txt`.
I have manually extracted the `Vocabulary/ORBvoc.txt.tar.gz` file to get `Vocabulary/ORBvoc.txt`.

**Comment by luigifreda** [comment]
Interesting, that should have been automatically done by `./gen_bin_vocabulary.sh` in the `build.sh` script ...

**Comment by FraDePace** [comment]
I might have found out the issue: when calling `./build.sh`, I get the following error:
```shell
[ 98%] Linking CXX executable /home/francesco/Projects/plvs/Examples_old/Monocular-Inertial/mono_inertial_tum_vi_old
[ 98%] Built target mono_inertial_tum_vi_old
[ 99%] Linking CXX executable /home/francesco/Projects/plvs/Examples_old/Stereo-Inertial/stereo_inertial_tum_vi_old
[ 99%] Built target stereo_inertial_tum_vi_old
[100%] Linking CXX executable /home/francesco/Projects/plvs/Examples_old/Stereo-Inertial/stereo_inertial_euroc_old
[100%] Built target stereo_inertial_euroc_old
./gen_bin_vocabulary.sh: line 12: config.sh: No such file or directory
``` 



I think that  `./gen_bin_vocabulary.sh` calls `. config.sh` after having already switched to the Vocabulary folder (`cd Vocabulary`). 

```shell
#!/usr/bin/env bash

# ====================================================
set -e

START_DIR=`pwd`

cd Vocabulary

if [ ! -f ORBvoc.bin ] && [ -f bin_vocabulary ]; then

	. config.sh  # source configuration file 
	
	print_blue '================================================'
	print_blue "Building Vocabulary"
	print_blue '================================================'


	if [ ! -f ORBvoc.txt ]; then
		echo "Uncompress vocabulary ..."
		tar -xf ORBvoc.txt.tar.gz
	fi	

	if [ ! -f ORBvoc.bin ] && [ -f bin_vocabulary ]; then
		echo "Converting vocabulary to binary version"
		./bin_vocabulary
	fi

	echo "done"
fi

cd $START_DIR
``` 

is it ok to call instead `. $START_DIR/config.sh" ?  What is the purpose of calling config.sh?

**Comment by luigifreda** [comment]
Thank you very much, Francesco! Fixed.
